# Path to your oh-my-zsh configuration.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
export ZSH_THEME="ptierno"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git)

source $ZSH/oh-my-zsh.sh

# Exports
export PATH=/Users/ptierno/Applications/eclipse:/Users/ptierno/bin:/usr/local/git/bin:/Users/ptierno/bin/maps/bin:/Users/ptierno/.gems/bin:/Users/ptierno/homebrew/bin:$PATH
export PYTHONPATH=\"$(brew --prefix)/lib/python2.7/site-packages:\$PYTHONPATH\"
export EDITOR="vim"
export PERL5LIB=$PERL5LIB:~/perl/lib
export MANPATH=$MANPATH:~/perl/man
export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagaced
export ROLE=~/Projects/puppet/role
export CORE=~/Projects/puppet/core
export APP=~/Projects/puppet/app
export HIERA=~/Projects/puppet/hiera
export SPEC_OPTS='--format documentation --color'

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting

#rvm
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

shifty=~/Documents/shifty/shifty.`date +%Y%m%d`
